### ISSUE TITLE
How to set a webp image to WebpImageView at runtime?

### ISSUE THREAD

**Issue by gitanshu** [EverythingMe/webp-android#2]

**Comment by rotemmiz** [comment]
Every setting of resource in xml (pngs and jpgs are no exception) is basically translated to a decoded stream (==bitmap) which is then set into the ImageView. So your easiest option would be:

```
import me.everything.webp.WebPDecoder

Bitmap bitmap = WebPDecoder.getInstance().decodeWebP(bytes); 
```

**Comment by rotemmiz** [comment]
I'm closing this issue.
